default:
  image: node:lts-alpine3.23
  cache:
    key: npm-cache
    paths:
      - .npm/

stages:
  - test

svg_validator:
  stage: test
  script:
    - npm ci --cache .npm --prefer-offline
    - node check_logos.js
